export const Types = [
    {'key': 'type', 'name': 'Tipo', 'color': '#999999', 'TextColor': '#000000'},
    {'key': 'grass', 'name': 'Grama', 'color': '#00C572', 'TextColor': '#FFFFFF'},
    {'key': 'fire', 'name': 'Fogo', 'color': '#FF0000' , 'TextColor': '#FFFFFF'},
    {'key': 'water', 'name': 'Água', 'color': '#0000FF' , 'TextColor': '#FFFFFF'},
    {'key': 'bug', 'name': 'Inseto', 'color': '#72E779' , 'TextColor': '#000000'},
    {'key': 'normal', 'name': 'Normal', 'color': '#999999' , 'TextColor': '#FFFFFF'},
    {'key': 'electric', 'name': 'Elétrico', 'color': '#FFFF00' , 'TextColor': '#000000'},
    {'key': 'ground', 'name': 'Terra', 'color': '#FFA500' , 'TextColor': '#000000'},
    {'key': 'fairy', 'name': 'Fada', 'color': '#FF448B' , 'TextColor': '#FFFFFF'},
    {'key': 'fighting', 'name': 'Lutador', 'color': '#FFA500' , 'TextColor': '#000000'},
    {'key': 'psychic', 'name': 'Psíquico', 'color': '#FF00FF' , 'TextColor': '#FFFFFF'},
    {'key': 'poison', 'name': 'Veneno', 'color': '#B005DB' , 'TextColor': '#FFFFFF'},
    {'key': 'flying', 'name': 'Voador', 'color': '#BDB9B8' , 'TextColor': '#FFFFFF'},
    {'key': 'ghost', 'name': 'Fantasma', 'color': '#800080' , 'TextColor': '#FFFFFF'},
    {'key': 'ice', 'name': 'Gelo', 'color': '#00FFFF' , 'TextColor': '#000000'},
    {'key': 'rock', 'name': 'Pedra', 'color': '#FFA500' , 'TextColor': '#000000'},
    {'key': 'steel', 'name': 'Aço', 'color': '#FFFFFF' , 'TextColor': '#000000'},
    {'key': 'dragon', 'name': 'Dragão', 'color': '#800080' , 'TextColor': '#FFFFFF'},
]